In [111]:
### Question 1: Array Creation and Manipulation

In [112]:
import numpy as np
import pandas as pd

In [113]:
#**Q1.1:** Create a 4x4 identity matrix using `np.eye()`
N=np.eye(4)
N

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [114]:
#**Q1.2:** Create an array of 8 zeros using `np.zeros()`
N=np.zeros(8)
N

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [115]:
#**Q1.3:** Create an array of 6 ones using `np.ones()`
N=np.ones(6)
N

array([1., 1., 1., 1., 1., 1.])

In [116]:
#**Q1.4:** Create an array with values from 0 to 15 using `np.arange()`
N=np.arange(16)
N


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [117]:
#**Q1.5:** Create an array with 8 evenly spaced values from 0 to 100 using `np.linspace()`
N=np.linspace(0,100,8)
N

array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])

In [118]:
### Question 2: Array Attributes and Information

In [119]:
banking_industry = np.array([
    # Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active
    [11, 25000, 300, 1200, 10],
    [12, 32000, 450, 1560, 15],
    [13, 28000, 380, 1100, 18],
    [14, 42000, 500, 1600, 20],
    [15, 35000, 420, 1400, 12],
    [16, 27000, 360, 1300, 19],
    [17, 49000, 480, 1700, 18],
    [18, 30000, 410, 1250, 14],
    [19, 45000, 550, 1800, 15],
    [20, 33000, 410, 1450, 11]
])

print(banking_industry)

[[   11 25000   300  1200    10]
 [   12 32000   450  1560    15]
 [   13 28000   380  1100    18]
 [   14 42000   500  1600    20]
 [   15 35000   420  1400    12]
 [   16 27000   360  1300    19]
 [   17 49000   480  1700    18]
 [   18 30000   410  1250    14]
 [   19 45000   550  1800    15]
 [   20 33000   410  1450    11]]


In [120]:
#**Q2.1:** What is the shape of the `banking_data` array?
print(banking_industry.shape)

(10, 5)


In [121]:
#**Q2.2:** What is the data type of the `banking_data` array?
print(banking_industry.dtype)

int32


In [122]:
#**Q2.3:** What is the size (total number of elements) of the `banking_data` array?
print(banking_industry.size)

50


In [123]:
#**Q2.4:** What is the number of dimensions of the `banking_data` array?
print(banking_industry.ndim)


2


In [124]:
#**Q2.5:** What is the memory size of the `banking_data` array in bytes?
print(banking_industry.nbytes)

200


In [125]:
### Question 3: Indexing and Slicing

In [126]:
#**Q3.1:** Extract the first row of `banking_data`
N=banking_industry[0]
N

array([   11, 25000,   300,  1200,    10])

In [127]:
#**Q3.2:** Extract the last row of `banking_data`
N=banking_industry[9]
N

array([   20, 33000,   410,  1450,    11])

In [128]:
#**Q3.3:** Extract the Account_Balance column (column index 1)
N=banking_industry[:,1]
N


array([25000, 32000, 28000, 42000, 35000, 27000, 49000, 30000, 45000,
       33000])

In [129]:
#**Q3.4:** Extract the first 4 rows and first 3 columns
N=banking_industry[:4,:3]
N

array([[   11, 25000,   300],
       [   12, 32000,   450],
       [   13, 28000,   380],
       [   14, 42000,   500]])

In [130]:
#**Q3.5:** Extract rows 3 to 7 (inclusive)
N=banking_industry[3:7]
N

array([[   14, 42000,   500,  1600,    20],
       [   15, 35000,   420,  1400,    12],
       [   16, 27000,   360,  1300,    19],
       [   17, 49000,   480,  1700,    18]])

In [131]:
### Question 4: Mathematical Operations

In [132]:
#**Q4.1:** Calculate the sum of all account balances
N=np.sum(banking_industry[:,1])
N

346000

In [133]:
#**Q4.2:** Calculate the mean account balance
N=np.mean(banking_industry[:,1])
N

34600.0

In [134]:
#**Q4.3:** Calculate the standard deviation of account balances
N=np.std(banking_industry[:,1])
N

7709.734106958554

In [135]:
#**Q4.4:** Calculate the variance of account balances
N=np.var(banking_industry[:,1])
N

59440000.0

In [136]:
#**Q4.5:** Calculate the median account balance
N=np.median(banking_industry[:,1])
N

32500.0

In [137]:
### Question 5: Statistical Functions


In [138]:
#**Q5.1:** Find the minimum and maximum account balances
min_bal=np.min(banking_industry[:,1])
max_bal=np.max(banking_industry[:,1])
min_bal,max_bal

(25000, 49000)

In [139]:
#**Q5.2:** Find the minimum and maximum credit scores
min_cr=np.min(banking_industry[:,2])
max_cr=np.max(banking_industry[:,2])
min_cr,max_cr

(300, 550)

In [140]:
#**Q5.3:** Calculate the percentile values for account balances (25th, 50th, 75th)
per=np.percentile(banking_industry[:,1],[25,50,75])
per

array([28500., 32500., 40250.])

In [141]:
#**Q5.4:** Calculate the correlation between account balance and credit score
cor=np.corrcoef(banking_industry[:,1],banking_industry[:,2])[0,1]
cor

0.8801652070665131

In [142]:
#**Q5.5:** Calculate the covariance between account balance and credit score
cova=np.cov(banking_industry[:,1],banking_industry[:,2])[0,1]
cova

518222.2222222222

In [143]:
### Question 6: Array Reshaping and Manipulation

In [144]:
#**Q6.1:** Reshape the `banking_data` to 5 rows × 10 columns
resh=banking_industry.reshape(5,10)
resh


array([[   11, 25000,   300,  1200,    10,    12, 32000,   450,  1560,
           15],
       [   13, 28000,   380,  1100,    18,    14, 42000,   500,  1600,
           20],
       [   15, 35000,   420,  1400,    12,    16, 27000,   360,  1300,
           19],
       [   17, 49000,   480,  1700,    18,    18, 30000,   410,  1250,
           14],
       [   19, 45000,   550,  1800,    15,    20, 33000,   410,  1450,
           11]])

In [145]:
#**Q6.2:** Flatten the `banking_data` to a 1D array
flat=banking_industry.flatten()
flat

array([   11, 25000,   300,  1200,    10,    12, 32000,   450,  1560,
          15,    13, 28000,   380,  1100,    18,    14, 42000,   500,
        1600,    20,    15, 35000,   420,  1400,    12,    16, 27000,
         360,  1300,    19,    17, 49000,   480,  1700,    18,    18,
       30000,   410,  1250,    14,    19, 45000,   550,  1800,    15,
          20, 33000,   410,  1450,    11])

In [146]:
#**Q6.3:** Transpose the `banking_data`
trans=banking_industry.transpose()
trans

array([[   11,    12,    13,    14,    15,    16,    17,    18,    19,
           20],
       [25000, 32000, 28000, 42000, 35000, 27000, 49000, 30000, 45000,
        33000],
       [  300,   450,   380,   500,   420,   360,   480,   410,   550,
          410],
       [ 1200,  1560,  1100,  1600,  1400,  1300,  1700,  1250,  1800,
         1450],
       [   10,    15,    18,    20,    12,    19,    18,    14,    15,
           11]])

In [170]:
#**Q6.4:** Split the `banking_data` into 2 equal parts vertically
sp=np.vsplit(banking_industry,2)
sp[0]
sp[1]

array([[   16, 27000,   360,  1300,    19],
       [   17, 49000,   480,  1700,    18],
       [   18, 30000,   410,  1250,    14],
       [   19, 45000,   550,  1800,    15],
       [   20, 33000,   410,  1450,    11]])

In [177]:
#**Q6.5:** Split the `banking_data` into 2 equal parts horizontally
ph=np.hsplit(banking_industry,2)
ph[0]
ph[1]

ValueError: array split does not result in an equal division

In [149]:
### Question 7: Logical Operations and Filtering


In [150]:
#**Q7.1:** Find customers with account balance greater than $100,000
cus=banking_industry[banking_industry[:,1]>100000].shape
cus

(0, 5)

In [151]:
#**Q7.2:** Find customers with credit score greater than 800
cus=banking_industry[banking_industry[:,2]>800].shape
cus

(0, 5)

In [180]:
#**Q7.3:** Find customers with transaction count greater than 50 AND credit score less than 750
cs=banking_industry[(banking_industry[:,3]>50) & (banking_industry[:,2]<750)]
cs

array([[   11, 25000,   300,  1200,    10],
       [   12, 32000,   450,  1560,    15],
       [   13, 28000,   380,  1100,    18],
       [   14, 42000,   500,  1600,    20],
       [   15, 35000,   420,  1400,    12],
       [   16, 27000,   360,  1300,    19],
       [   17, 49000,   480,  1700,    18],
       [   18, 30000,   410,  1250,    14],
       [   19, 45000,   550,  1800,    15],
       [   20, 33000,   410,  1450,    11]])

In [153]:
#**Q7.4:** Count how many customers have account balance between $10,000 and $100,000
cus1=np,sum((banking_industry[:,1]>=10000) & (banking_industry[:,1]<=100000))
cus1

(<module 'numpy' from 'c:\\ProgramData\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>,
 10)

In [154]:
#**Q7.5:** Find the index of the customer with the highest credit score
hcs=np.argmax(banking_industry[:,2])+1
hcs

9

In [155]:
#### Question 8: Sorting and Searching

In [156]:
#**Q8.1:** Sort the `banking_data` by account balance (ascending)
s=banking_industry[banking_industry[:,1].argsort()]
s

array([[   11, 25000,   300,  1200,    10],
       [   16, 27000,   360,  1300,    19],
       [   13, 28000,   380,  1100,    18],
       [   18, 30000,   410,  1250,    14],
       [   12, 32000,   450,  1560,    15],
       [   20, 33000,   410,  1450,    11],
       [   15, 35000,   420,  1400,    12],
       [   14, 42000,   500,  1600,    20],
       [   19, 45000,   550,  1800,    15],
       [   17, 49000,   480,  1700,    18]])

In [157]:
#**Q8.2:** Sort the `banking_data` by credit score (descending)
sr=banking_industry[(-banking_industry[:,2]).argsort()]
sr

array([[   19, 45000,   550,  1800,    15],
       [   14, 42000,   500,  1600,    20],
       [   17, 49000,   480,  1700,    18],
       [   12, 32000,   450,  1560,    15],
       [   15, 35000,   420,  1400,    12],
       [   18, 30000,   410,  1250,    14],
       [   20, 33000,   410,  1450,    11],
       [   13, 28000,   380,  1100,    18],
       [   16, 27000,   360,  1300,    19],
       [   11, 25000,   300,  1200,    10]])

In [158]:
#**Q8.3:** Find the indices that would sort the array by years active
ins=np.argsort(banking_industry[:,1])
ins

array([0, 5, 2, 7, 1, 9, 4, 3, 8, 6], dtype=int64)

In [160]:
#**Q8.4:** Find the customer with the second highest account balance
sha=np.argsort(banking_industry[:,1])[-2]
shab=banking_industry[sha]
shab

array([   19, 45000,   550,  1800,    15])

In [162]:
#**Q8.5:** Find the customer with the lowest transaction count
lt=np.argmin(banking_industry[:,3])
ltc=banking_industry[lt]
ltc

array([   13, 28000,   380,  1100,    18])

In [ ]:
### Question 9: Mathematical Functions

In [ ]:
#**Q9.1:** Calculate the absolute values of all elements
ab=np.abs(banking_industry)
ab

array([[   11, 25000,   300,  1200,    10],
       [   12, 32000,   450,  1560,    15],
       [   13, 28000,   380,  1100,    18],
       [   14, 42000,   500,  1600,    20],
       [   15, 35000,   420,  1400,    12],
       [   16, 27000,   360,  1300,    19],
       [   17, 49000,   480,  1700,    18],
       [   18, 30000,   410,  1250,    14],
       [   19, 45000,   550,  1800,    15],
       [   20, 33000,   410,  1450,    11]])

In [ ]:
#**Q9.2:** Calculate the square root of all account balances
sq=np.sqrt(banking_industry[:,1])
sq

array([158.11388301, 178.8854382 , 167.33200531, 204.93901532,
       187.08286934, 164.31676725, 221.35943621, 173.20508076,
       212.13203436, 181.65902125])

In [ ]:
#**Q9.3:** Calculate the square of all credit scores
sq=np.sqrt(banking_industry[:,2])
sq

array([17.32050808, 21.21320344, 19.49358869, 22.36067977, 20.49390153,
       18.97366596, 21.9089023 , 20.24845673, 23.4520788 , 20.24845673])

In [ ]:
#**Q9.4:** Calculate the exponential of all transaction counts
ex=np.exp(banking_industry[:,3])
ex

C:\Users\abhi\AppData\Local\Temp\ipykernel_29212\2934033888.py:2: RuntimeWarning: overflow encountered in exp
  ex=np.exp(banking_industry[:,3])


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [ ]:
#**Q9.5:** Calculate the natural logarithm of all account balances
lg=np.log(banking_industry[:,1])
lg

array([10.1266311 , 10.37349118, 10.23995979, 10.6454249 , 10.46310334,
       10.20359214, 10.79957558, 10.30895266, 10.71441777, 10.40426284])

In [ ]:
### Question 10: Advanced Operations

In [ ]:
#**Q10.1:** Calculate the cumulative sum of account balances
cms=np.cumsum(banking_industry[:,1])
cms

array([ 25000,  57000,  85000, 127000, 162000, 189000, 238000, 268000,
       313000, 346000])

In [ ]:
#**Q10.2:** Calculate the cumulative product of transaction counts
cm=np.cumprod(banking_industry[:,3])
cm

array([       1200,     1872000,  2059200000,   480083968,  2102657024,
        1854930944,   876609536,   545259520, -2080374784, -1476395008])

In [ ]:
#**Q10.3:** Calculate the difference between consecutive account balances
cn=np.diff(banking_industry[:,1])
cn

array([  7000,  -4000,  14000,  -7000,  -8000,  22000, -19000,  15000,
       -12000])

In [ ]:
#**Q10.4:** Calculate the gradient of account balances
gt=np.gradient(banking_industry[:,1])
gt

array([  7000.,   1500.,   5000.,   3500.,  -7500.,   7000.,   1500.,
        -2000.,   1500., -12000.])

In [ ]:
#**Q10.5:** Calculate the histogram of account balances with 5 bins


In [ ]:
### Question 11: Random Numbers and Simulation

In [ ]:
#**Q11.1:** Generate 6 random integers between 1 and 1000
rd=np.random.randint(1,1001,6)
rd

array([255, 190, 369, 976, 193, 877])

In [ ]:
#**Q11.2:** Generate 6 random floats between 0 and 1
rf=np.random.random(6)
rf

array([0.06842323, 0.59592095, 0.52847972, 0.61165618, 0.53342521,
       0.10293231])

In [ ]:
#**Q11.3:** Generate 6 random numbers from normal distribution (mean=700, std=100)
rn=np.random.normal(0,1,6)
rn


array([ 1.24087862, -0.24800583,  0.40550918, -1.18351923, -1.51219593,
       -0.5678708 ])

In [ ]:
#**Q11.4:** Shuffle the `banking_data` rows randomly
sf=banking_industry.copy()
np.random.shuffle(sf)
sf

array([[   18, 30000,   410,  1250,    14],
       [   19, 45000,   550,  1800,    15],
       [   20, 33000,   410,  1450,    11],
       [   13, 28000,   380,  1100,    18],
       [   16, 27000,   360,  1300,    19],
       [   14, 42000,   500,  1600,    20],
       [   12, 32000,   450,  1560,    15],
       [   17, 49000,   480,  1700,    18],
       [   11, 25000,   300,  1200,    10],
       [   15, 35000,   420,  1400,    12]])

In [ ]:
#**Q11.5:** Set random seed to 123 and generate 4 random numbers
np.random.seed(123)
srs=np.random.random(4)
srs

array([0.69646919, 0.28613933, 0.22685145, 0.55131477])

In [ ]:
### Question 12: Linear Algebra Operations

In [ ]:
#**Q12.1:** Calculate the dot product of account balance and credit score columns
dp=np.dot((banking_industry[:,1]),(banking_industry[:,2]))
dp

152060000

In [ ]:
#**Q12.2:** Calculate the cross product of first two rows
cp=np.cross(banking_industry[0,:3],banking_industry[1,:3])
cp

array([1650000,   -1350,   52000])

In [ ]:
#**Q12.3:** Calculate the norm (magnitude) of the account balance column
nor=np.linalg.norm(banking_industry[:,1])
nor

112098.1712607302

In [ ]:
#**Q12.4:** Create a 3x3 matrix and calculate its determinant
mat=np.array([[1,4,2],[2,5,6],[4,3,6]])
cd=np.linalg.det(mat)
cd

32.000000000000014

In [ ]:
#**Q12.5:** Calculate the inverse of the 3x3 matrix
im=np.linalg.inv(mat)
im

array([[ 0.375  , -0.5625 ,  0.4375 ],
       [ 0.375  , -0.0625 , -0.0625 ],
       [-0.4375 ,  0.40625, -0.09375]])

In [ ]:
### Question 13: String Operations

In [ ]:
#**Q13.1:** Convert all customer IDs to strings
cu=banking_industry[:,0].astype(str)
cu

array(['11', '12', '13', '14', '15', '16', '17', '18', '19', '20'],
      dtype='<U11')

In [ ]:
#**Q13.2:** Check if any customer ID contains '100'
id=np.char.find(cu,'100')>=0
id

array([False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
#**Q13.3:** Convert all customer IDs to uppercase (if they were strings)
up=np.char.upper(cu)
up

array(['11', '12', '13', '14', '15', '16', '17', '18', '19', '20'],
      dtype='<U11')

In [ ]:
#**Q13.4:** Count the length of each customer ID string
ln=np.char.str_len(cu)
ln

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
#**Q13.5:** Replace '100' with 'CUST' in customer IDs
rp=np.char.replace(cu,'100','CUST')
rp

array(['11', '12', '13', '14', '15', '16', '17', '18', '19', '20'],
      dtype='<U2')

In [ ]:
#### Question 14: Date and Time Operations

In [ ]:
#**Q14.1:** Convert years active to months
ym=banking_industry[:,4]*12
ym


array([120, 180, 216, 240, 144, 228, 216, 168, 180, 132])

In [ ]:
#**Q14.2:** Calculate the average years active
ay=np.average(banking_industry[:,4])
ay

15.2

In [ ]:
#**Q14.3:** Find customers who have been active for more than 5 years
ac=banking_industry[banking_industry[:,4]>5]
ac

array([[   11, 25000,   300,  1200,    10],
       [   12, 32000,   450,  1560,    15],
       [   13, 28000,   380,  1100,    18],
       [   14, 42000,   500,  1600,    20],
       [   15, 35000,   420,  1400,    12],
       [   16, 27000,   360,  1300,    19],
       [   17, 49000,   480,  1700,    18],
       [   18, 30000,   410,  1250,    14],
       [   19, 45000,   550,  1800,    15],
       [   20, 33000,   410,  1450,    11]])

In [ ]:
#**Q14.4:** Calculate the total time all customers have been active (in years)
atc=np.sum(banking_industry[:,4])
atc

152

In [ ]:
#**Q14.5:** Find the customer with the shortest time active
sa=np.argmin(banking_industry[:,4])
sta=banking_industry[sa]
sta

array([   11, 25000,   300,  1200,    10])

In [ ]:
### Question 15: Advanced Array Operations

In [ ]:
#**Q15.1:** Apply a function to calculate 5% interest on all account balances


In [ ]:
#**Q15.2:** Use `np.where` to categorize customers by balance ranges
cc=np.where(banking_industry[:,1])
cc

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

In [ ]:
#**Q15.3:** Use `np.select` to categorize customers by credit score ranges
csr=(np.select,banking_industry[:,2])
csr

(<function numpy.select(condlist, choicelist, default=0)>,
 array([300, 450, 380, 500, 420, 360, 480, 410, 550, 410]))

In [ ]:
#**Q15.4:** Use `np.piecewise` to apply different interest rates based on balance


In [ ]:
#**Q15.5:** Use `np.apply_along_axis` to calculate the sum of each row


In [ ]:
### Question 16: Array Concatenation and Stacking

In [ ]:
#**Q16.1:** Concatenate two arrays horizontally using `np.hstack()`
ar1=np.array([5,6,7])
ar2=np.array([1,2,3])
hs=np.hstack([ar1,ar2])
hs

array([5, 6, 7, 1, 2, 3])

In [ ]:
#**Q16.2:** Concatenate two arrays vertically using `np.vstack()`
vs=np.vstack([ar1,ar2])
vs

array([[5, 6, 7],
       [1, 2, 3]])

In [ ]:
#**Q16.3:** Concatenate arrays along a specific axis using `np.concatenate()`
con=np.concatenate([ar1,ar2])
con

array([5, 6, 7, 1, 2, 3])

In [ ]:
#**Q16.4:** Stack arrays depth-wise using `np.dstack()`
st=np.dstack([ar1,ar2])
st

array([[[5, 1],
        [6, 2],
        [7, 3]]])

In [ ]:
#**Q16.5:** Create a column stack using `np.column_stack()`
cln=np.column_stack([ar1,ar2])
cln

array([[5, 1],
       [6, 2],
       [7, 3]])

In [ ]:
### Question 17: Array Splitting Operations

In [ ]:
#**Q17.1:** Split an array into 3 equal parts using `np.split()`
sp=np.array([1,3,5,7,9,2,4,6,8])
sla=np.split(sp, 3)
print(sla)
for i,part in enumerate(sla):
    print(sla)

[array([1, 3, 5]), array([7, 9, 2]), array([4, 6, 8])]
[array([1, 3, 5]), array([7, 9, 2]), array([4, 6, 8])]
[array([1, 3, 5]), array([7, 9, 2]), array([4, 6, 8])]
[array([1, 3, 5]), array([7, 9, 2]), array([4, 6, 8])]


In [ ]:
#**Q17.2:** Split an array at specific indices using `np.split()`
si=np.split(sp,[7,9,2])
print(si)
for i,part in enumerate(si):
    print(si)

[array([1, 3, 5, 7, 9, 2, 4]), array([6, 8]), array([], dtype=int32), array([5, 7, 9, 2, 4, 6, 8])]
[array([1, 3, 5, 7, 9, 2, 4]), array([6, 8]), array([], dtype=int32), array([5, 7, 9, 2, 4, 6, 8])]
[array([1, 3, 5, 7, 9, 2, 4]), array([6, 8]), array([], dtype=int32), array([5, 7, 9, 2, 4, 6, 8])]
[array([1, 3, 5, 7, 9, 2, 4]), array([6, 8]), array([], dtype=int32), array([5, 7, 9, 2, 4, 6, 8])]
[array([1, 3, 5, 7, 9, 2, 4]), array([6, 8]), array([], dtype=int32), array([5, 7, 9, 2, 4, 6, 8])]


In [ ]:
#**Q17.3:** Split an array horizontally using `np.hsplit()`
sp=np.array([1,3,5,7,9,2,4,6,8])
sh=np.hsplit(sp, 3)
print(sh)
for i,part in enumerate(sh):
    print(sh)

[array([1, 3, 5]), array([7, 9, 2]), array([4, 6, 8])]
[array([1, 3, 5]), array([7, 9, 2]), array([4, 6, 8])]
[array([1, 3, 5]), array([7, 9, 2]), array([4, 6, 8])]
[array([1, 3, 5]), array([7, 9, 2]), array([4, 6, 8])]


In [ ]:
#**Q17.4:** Split an array vertically using `np.vsplit()`
A=np.vsplit(sp, 2)
print(A)
for i,part in enumerate(A):
    print(A)

ValueError: vsplit only works on arrays of 2 or more dimensions

In [ ]:
#**Q17.5:** Split an array into equal chunks using `np.array_split()`
ch=np.array_split(sp,4)
print(ch)
for i,chunk in enumerate(ch):
    print(ch)

[array([1, 3, 5]), array([7, 9]), array([2, 4]), array([6, 8])]
[array([1, 3, 5]), array([7, 9]), array([2, 4]), array([6, 8])]
[array([1, 3, 5]), array([7, 9]), array([2, 4]), array([6, 8])]
[array([1, 3, 5]), array([7, 9]), array([2, 4]), array([6, 8])]
[array([1, 3, 5]), array([7, 9]), array([2, 4]), array([6, 8])]


In [ ]:
### Question 18: Array Repetition and Tiling

In [ ]:
#**Q18.1:** Repeat each element of an array 3 times using `np.repeat()`
nrp=np.repeat(ar1,3)
nrp

array([5, 5, 5, 6, 6, 6, 7, 7, 7])

In [ ]:
#**Q18.2:** Repeat an entire array 2 times using `np.tile()`
nt=np.tile(ar2,2)
nt

array([1, 2, 3, 1, 2, 3])

In [ ]:
#**Q18.3:** Repeat a 2D array using `np.tile()`
W=np.array([[1,2,4],[3,4,6]])
dt=np.tile(W,(2,3))
dt

array([[1, 2, 4, 1, 2, 4, 1, 2, 4],
       [3, 4, 6, 3, 4, 6, 3, 4, 6],
       [1, 2, 4, 1, 2, 4, 1, 2, 4],
       [3, 4, 6, 3, 4, 6, 3, 4, 6]])

In [ ]:
#**Q18.4:** Create a pattern using `np.tile()`
pt=np.array([1,2])
ptl=np.tile(pt,6)
ptl

array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2])

In [ ]:
#**Q18.5:** Repeat elements with different counts using `np.repeat()`
rep=[6,9,5]
cr=np.repeat(ar1,rep)
cr

array([5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7])

In [ ]:
### Question 19: Array Comparison and Logical Operations

In [183]:
#**Q19.1:** Compare two arrays for equality using `np.array_equal()`
arr1=([2,3,4])
arr2=([2,3,4])
arr3=([2,7,6])
np.array_equal(arr1,arr2)
np.array_equal(arr1,arr3)

False

In [185]:
#**Q19.2:** Check if arrays are close using `np.allclose()`
arr4=([7,8,9])
arr5=([7.001,8.001,9.001])
np.allclose(arr4,arr5,atol=0.001)

True

In [190]:
#**Q19.3:** Apply logical AND operation between arrays
la=np.logical_and(arr1>1,arr1<3)
la

TypeError: '>' not supported between instances of 'list' and 'int'

In [191]:
#**Q19.4:** Apply logical OR operation between arrays
l=np.logical_or(arr1==1,arr1==3)
l

False

In [193]:
#**Q19.5:** Apply logical NOT operation to an array
lp=np.logical_not(arr2==2)
lp

True

In [ ]:
### Question 20: Array Set Operations

In [195]:
#**Q20.1:** Find unique elements in an array using `np.unique()`
u=np.array([1,2,2,4,5,5,5])
ue=np.unique(u)
ue

array([1, 2, 4, 5])

In [196]:
#**Q20.2:** Find the intersection of two arrays using `np.intersect1d()`
arr6=np.array([2,3,4,5,6])
arr7=np.array([5,6,7,8,9])
ta=np.intersect1d(arr6,arr7)
ta

array([5, 6])

In [197]:
#**Q20.3:** Find the union of two arrays using `np.union1d()`
ua=np.union1d(arr6,arr7)
ua

array([2, 3, 4, 5, 6, 7, 8, 9])

In [198]:
#**Q20.4:** Find elements in first array but not in second using `np.setdiff1d()`
sd=np.setdiff1d(arr6,arr7)
sd

array([2, 3, 4])

In [199]:
#**Q20.5:** Find the symmetric difference between two arrays using `np.setxor1d()`
sx=np.setxor1d(arr6,arr7)
sx

array([2, 3, 4, 7, 8, 9])