In [130]:
### Question 1: Array Creation and Manipulation

In [131]:
import numpy as np
import pandas as pd

In [132]:
#**Q1.1:** Create a 4x4 identity matrix using `np.eye()`
N=np.eye(4)
print(N)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [133]:
#**Q1.2:** Create an array of 8 zeros using `np.zeros()`
N=np.zeros(8)
print(N)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [134]:
#**Q1.3:** Create an array of 6 ones using `np.ones()`
N=np.ones(6)
print(N)

[1. 1. 1. 1. 1. 1.]


In [135]:
#**Q1.4:** Create an array with values from 0 to 15 using `np.arange()`
N=np.arange(16)
print(N)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [136]:
#**Q1.5:** Create an array with 8 evenly spaced values from 0 to 100 using `np.linspace()`
N=np.linspace(0,100,8)
print(N)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [137]:
### Question 2: Array Attributes and Information

In [138]:
#The assignment uses banking industry data with 10 rows × 5 columns:
#- **Customer_ID**: Unique identifier for each customer
#- **Account_Balance**: Customer's account balance in dollars
#- **Credit_Score**: Customer's credit score (300-900 range)
#- **Transaction_Count**: Number of transactions in the last month
#- **Years_Active**: Number of years the customer has been with the bank

import numpy as np
banking_industry= np.array([
(901,127.74,690,27,11),
(902,7804.82,865,26,18),
(900,7233.57,312,11,16),
(904,4966.56,303,18,19),
(905,7811.21,683,13,17),
(906,3703.61,369,50,14),
(907,6702.98,679,35,7),
(908,8128.51,495,43,16),
(909,5581.68,302,17,21),
(910,9078.88,773,35,3)
])
banking_industry


array([[9.01000e+02, 1.27740e+02, 6.90000e+02, 2.70000e+01, 1.10000e+01],
       [9.02000e+02, 7.80482e+03, 8.65000e+02, 2.60000e+01, 1.80000e+01],
       [9.00000e+02, 7.23357e+03, 3.12000e+02, 1.10000e+01, 1.60000e+01],
       [9.04000e+02, 4.96656e+03, 3.03000e+02, 1.80000e+01, 1.90000e+01],
       [9.05000e+02, 7.81121e+03, 6.83000e+02, 1.30000e+01, 1.70000e+01],
       [9.06000e+02, 3.70361e+03, 3.69000e+02, 5.00000e+01, 1.40000e+01],
       [9.07000e+02, 6.70298e+03, 6.79000e+02, 3.50000e+01, 7.00000e+00],
       [9.08000e+02, 8.12851e+03, 4.95000e+02, 4.30000e+01, 1.60000e+01],
       [9.09000e+02, 5.58168e+03, 3.02000e+02, 1.70000e+01, 2.10000e+01],
       [9.10000e+02, 9.07888e+03, 7.73000e+02, 3.50000e+01, 3.00000e+00]])

In [139]:
#**Q2.1:** What is the shape of the `banking_data` array?
print(banking_industry.shape)

(10, 5)


In [140]:
#**Q2.2:** What is the data type of the `banking_data` array?
print(banking_industry.data)

In [141]:
#**Q2.3:** What is the size (total number of elements) of the `banking_data` array?
print(banking_industry.size)

50


In [142]:
#**Q2.4:** What is the number of dimensions of the `banking_data` array?
print(banking_industry.ndim)


2


In [143]:
#**Q2.5:** What is the memory size of the `banking_data` array in bytes?
print(banking_industry.nbytes)

400


In [144]:
### Question 3: Indexing and Slicing


In [145]:
#**Q3.1:** Extract the first row of `banking_data`
N=banking_industry[0]
print(N)

[901.   127.74 690.    27.    11.  ]


In [146]:
#**Q3.2:** Extract the last row of `banking_data`
N=banking_industry[9]
print(N)

[9.10000e+02 9.07888e+03 7.73000e+02 3.50000e+01 3.00000e+00]


In [147]:
#**Q3.3:** Extract the Account_Balance column (column index 1)
N=banking_industry[:,1]
print(N)


[ 127.74 7804.82 7233.57 4966.56 7811.21 3703.61 6702.98 8128.51 5581.68
 9078.88]


In [148]:
#**Q3.4:** Extract the first 4 rows and first 3 columns
N=banking_industry[:4,:3]
print(N)

[[ 901.    127.74  690.  ]
 [ 902.   7804.82  865.  ]
 [ 900.   7233.57  312.  ]
 [ 904.   4966.56  303.  ]]


In [149]:
#**Q3.5:** Extract rows 3 to 7 (inclusive)
N=banking_industry[3:7]
print(N)

[[9.04000e+02 4.96656e+03 3.03000e+02 1.80000e+01 1.90000e+01]
 [9.05000e+02 7.81121e+03 6.83000e+02 1.30000e+01 1.70000e+01]
 [9.06000e+02 3.70361e+03 3.69000e+02 5.00000e+01 1.40000e+01]
 [9.07000e+02 6.70298e+03 6.79000e+02 3.50000e+01 7.00000e+00]]


In [150]:
### Question 4: Mathematical Operations

In [151]:
#**Q4.1:** Calculate the sum of all account balances
N=np.sum(banking_industry[:,1])
print(N)

61139.56


In [152]:
#**Q4.2:** Calculate the mean account balance
N=np.mean(banking_industry[:,1])
print(N)

6113.956


In [153]:
#**Q4.3:** Calculate the standard deviation of account balances
N=np.std(banking_industry[:,1])
print(N)

2518.606048842097


In [154]:
#**Q4.4:** Calculate the variance of account balances
N=np.var(banking_industry[:,1])
print(N)

6343376.429264


In [155]:
#**Q4.5:** Calculate the median account balance
N=np.median(banking_industry[:,1])
print(N)

6968.275


In [156]:
### Question 5: Statistical Functions


In [157]:
#**Q5.1:** Find the minimum and maximum account balances
min_bal=np.min(banking_industry[:,1])
max_bal=np.max(banking_industry[:,1])
min_bal,max_bal

(127.74, 9078.88)

In [158]:
#**Q5.2:** Find the minimum and maximum credit scores
min_cr=np.min(banking_industry[:,2])
max_cr=np.max(banking_industry[:,2])
min_cr,max_cr

(302.0, 865.0)

In [159]:
#**Q5.3:** Calculate the percentile values for account balances (25th, 50th, 75th)
per=np.percentile(banking_industry[:,1],[25,50,75])
per

array([5120.34  , 6968.275 , 7809.6125])

In [160]:
#**Q5.4:** Calculate the correlation between account balance and credit score
cor=np.corrcoef(banking_industry[:,1],banking_industry[:,2])[0,1]
cor

0.21987685564568069

In [161]:
#**Q5.5:** Calculate the covariance between account balance and credit score
cova=np.cov(banking_industry[:,1],banking_industry[:,2])[0,1]
cova

125762.68155555548

In [162]:
### Question 6: Array Reshaping and Manipulation

In [163]:
#**Q6.1:** Reshape the `banking_data` to 5 rows × 10 columns
resh=banking_industry.reshape(5,10)
resh


array([[9.01000e+02, 1.27740e+02, 6.90000e+02, 2.70000e+01, 1.10000e+01,
        9.02000e+02, 7.80482e+03, 8.65000e+02, 2.60000e+01, 1.80000e+01],
       [9.00000e+02, 7.23357e+03, 3.12000e+02, 1.10000e+01, 1.60000e+01,
        9.04000e+02, 4.96656e+03, 3.03000e+02, 1.80000e+01, 1.90000e+01],
       [9.05000e+02, 7.81121e+03, 6.83000e+02, 1.30000e+01, 1.70000e+01,
        9.06000e+02, 3.70361e+03, 3.69000e+02, 5.00000e+01, 1.40000e+01],
       [9.07000e+02, 6.70298e+03, 6.79000e+02, 3.50000e+01, 7.00000e+00,
        9.08000e+02, 8.12851e+03, 4.95000e+02, 4.30000e+01, 1.60000e+01],
       [9.09000e+02, 5.58168e+03, 3.02000e+02, 1.70000e+01, 2.10000e+01,
        9.10000e+02, 9.07888e+03, 7.73000e+02, 3.50000e+01, 3.00000e+00]])

In [164]:
#**Q6.2:** Flatten the `banking_data` to a 1D array
flat=banking_industry.flatten()
flat

array([9.01000e+02, 1.27740e+02, 6.90000e+02, 2.70000e+01, 1.10000e+01,
       9.02000e+02, 7.80482e+03, 8.65000e+02, 2.60000e+01, 1.80000e+01,
       9.00000e+02, 7.23357e+03, 3.12000e+02, 1.10000e+01, 1.60000e+01,
       9.04000e+02, 4.96656e+03, 3.03000e+02, 1.80000e+01, 1.90000e+01,
       9.05000e+02, 7.81121e+03, 6.83000e+02, 1.30000e+01, 1.70000e+01,
       9.06000e+02, 3.70361e+03, 3.69000e+02, 5.00000e+01, 1.40000e+01,
       9.07000e+02, 6.70298e+03, 6.79000e+02, 3.50000e+01, 7.00000e+00,
       9.08000e+02, 8.12851e+03, 4.95000e+02, 4.30000e+01, 1.60000e+01,
       9.09000e+02, 5.58168e+03, 3.02000e+02, 1.70000e+01, 2.10000e+01,
       9.10000e+02, 9.07888e+03, 7.73000e+02, 3.50000e+01, 3.00000e+00])

In [165]:
#**Q6.3:** Transpose the `banking_data`
trans=banking_industry.transpose()
trans

array([[9.01000e+02, 9.02000e+02, 9.00000e+02, 9.04000e+02, 9.05000e+02,
        9.06000e+02, 9.07000e+02, 9.08000e+02, 9.09000e+02, 9.10000e+02],
       [1.27740e+02, 7.80482e+03, 7.23357e+03, 4.96656e+03, 7.81121e+03,
        3.70361e+03, 6.70298e+03, 8.12851e+03, 5.58168e+03, 9.07888e+03],
       [6.90000e+02, 8.65000e+02, 3.12000e+02, 3.03000e+02, 6.83000e+02,
        3.69000e+02, 6.79000e+02, 4.95000e+02, 3.02000e+02, 7.73000e+02],
       [2.70000e+01, 2.60000e+01, 1.10000e+01, 1.80000e+01, 1.30000e+01,
        5.00000e+01, 3.50000e+01, 4.30000e+01, 1.70000e+01, 3.50000e+01],
       [1.10000e+01, 1.80000e+01, 1.60000e+01, 1.90000e+01, 1.70000e+01,
        1.40000e+01, 7.00000e+00, 1.60000e+01, 2.10000e+01, 3.00000e+00]])

In [166]:
#**Q6.4:** Split the `banking_data` into 2 equal parts vertically
sp=np.vsplit(banking_industry,2)
sp[0]
sp[1]

array([[9.06000e+02, 3.70361e+03, 3.69000e+02, 5.00000e+01, 1.40000e+01],
       [9.07000e+02, 6.70298e+03, 6.79000e+02, 3.50000e+01, 7.00000e+00],
       [9.08000e+02, 8.12851e+03, 4.95000e+02, 4.30000e+01, 1.60000e+01],
       [9.09000e+02, 5.58168e+03, 3.02000e+02, 1.70000e+01, 2.10000e+01],
       [9.10000e+02, 9.07888e+03, 7.73000e+02, 3.50000e+01, 3.00000e+00]])

In [170]:
#**Q6.5:** Split the `banking_data` into 2 equal parts horizontally


In [ ]:
### Question 7: Logical Operations and Filtering


In [ ]:
#**Q7.1:** Find customers with account balance greater than $100,000
cus=banking_industry[banking_industry[:,1]>100000].shape
cus

(0, 5)

In [179]:
#**Q7.2:** Find customers with credit score greater than 800
cus=banking_industry[banking_industry[:,2]>800].shape
cus

(1, 5)

In [ ]:
#**Q7.3:** Find customers with transaction count greater than 50 AND credit score less than 750


In [182]:
#**Q7.4:** Count how many customers have account balance between $10,000 and $100,000
cus1=np,sum((banking_industry[:,1]>=10000) & (banking_industry[:,1]<=100000))
cus1

(<module 'numpy' from 'c:\\ProgramData\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>,
 0)

In [184]:
#**Q7.5:** Find the index of the customer with the highest credit score
hcs=np.argmax(banking_industry[:,2])+1
hcs

2

In [ ]:
#### Question 8: Sorting and Searching

In [185]:
#**Q8.1:** Sort the `banking_data` by account balance (ascending)
s=banking_industry[banking_industry[:,1].argsort()]
s

array([[9.01000e+02, 1.27740e+02, 6.90000e+02, 2.70000e+01, 1.10000e+01],
       [9.06000e+02, 3.70361e+03, 3.69000e+02, 5.00000e+01, 1.40000e+01],
       [9.04000e+02, 4.96656e+03, 3.03000e+02, 1.80000e+01, 1.90000e+01],
       [9.09000e+02, 5.58168e+03, 3.02000e+02, 1.70000e+01, 2.10000e+01],
       [9.07000e+02, 6.70298e+03, 6.79000e+02, 3.50000e+01, 7.00000e+00],
       [9.00000e+02, 7.23357e+03, 3.12000e+02, 1.10000e+01, 1.60000e+01],
       [9.02000e+02, 7.80482e+03, 8.65000e+02, 2.60000e+01, 1.80000e+01],
       [9.05000e+02, 7.81121e+03, 6.83000e+02, 1.30000e+01, 1.70000e+01],
       [9.08000e+02, 8.12851e+03, 4.95000e+02, 4.30000e+01, 1.60000e+01],
       [9.10000e+02, 9.07888e+03, 7.73000e+02, 3.50000e+01, 3.00000e+00]])

In [188]:
#**Q8.2:** Sort the `banking_data` by credit score (descending)
sr=banking_industry[(-banking_industry[:,2]).argsort()]
sr

array([[9.02000e+02, 7.80482e+03, 8.65000e+02, 2.60000e+01, 1.80000e+01],
       [9.10000e+02, 9.07888e+03, 7.73000e+02, 3.50000e+01, 3.00000e+00],
       [9.01000e+02, 1.27740e+02, 6.90000e+02, 2.70000e+01, 1.10000e+01],
       [9.05000e+02, 7.81121e+03, 6.83000e+02, 1.30000e+01, 1.70000e+01],
       [9.07000e+02, 6.70298e+03, 6.79000e+02, 3.50000e+01, 7.00000e+00],
       [9.08000e+02, 8.12851e+03, 4.95000e+02, 4.30000e+01, 1.60000e+01],
       [9.06000e+02, 3.70361e+03, 3.69000e+02, 5.00000e+01, 1.40000e+01],
       [9.00000e+02, 7.23357e+03, 3.12000e+02, 1.10000e+01, 1.60000e+01],
       [9.04000e+02, 4.96656e+03, 3.03000e+02, 1.80000e+01, 1.90000e+01],
       [9.09000e+02, 5.58168e+03, 3.02000e+02, 1.70000e+01, 2.10000e+01]])

In [190]:
#**Q8.3:** Find the indices that would sort the array by years active
ins=np.argsort(banking_industry[:,1])
ins

array([0, 5, 3, 8, 6, 2, 1, 4, 7, 9], dtype=int64)

In [ ]:
#**Q8.4:** Find the customer with the second highest account balance


In [ ]:
#**Q8.5:** Find the customer with the lowest transaction count


In [ ]:
### Question 9: Mathematical Functions

In [191]:
#**Q9.1:** Calculate the absolute values of all elements
ab=np.abs(banking_industry)
ab

array([[9.01000e+02, 1.27740e+02, 6.90000e+02, 2.70000e+01, 1.10000e+01],
       [9.02000e+02, 7.80482e+03, 8.65000e+02, 2.60000e+01, 1.80000e+01],
       [9.00000e+02, 7.23357e+03, 3.12000e+02, 1.10000e+01, 1.60000e+01],
       [9.04000e+02, 4.96656e+03, 3.03000e+02, 1.80000e+01, 1.90000e+01],
       [9.05000e+02, 7.81121e+03, 6.83000e+02, 1.30000e+01, 1.70000e+01],
       [9.06000e+02, 3.70361e+03, 3.69000e+02, 5.00000e+01, 1.40000e+01],
       [9.07000e+02, 6.70298e+03, 6.79000e+02, 3.50000e+01, 7.00000e+00],
       [9.08000e+02, 8.12851e+03, 4.95000e+02, 4.30000e+01, 1.60000e+01],
       [9.09000e+02, 5.58168e+03, 3.02000e+02, 1.70000e+01, 2.10000e+01],
       [9.10000e+02, 9.07888e+03, 7.73000e+02, 3.50000e+01, 3.00000e+00]])

In [192]:
#**Q9.2:** Calculate the square root of all account balances
sq=np.sqrt(banking_industry[:,1])
sq

array([11.30221217, 88.34489233, 85.05039682, 70.47382493, 88.38105001,
       60.85729209, 81.87172894, 90.15824976, 74.71064181, 95.28315696])

In [193]:
#**Q9.3:** Calculate the square of all credit scores
sq=np.sqrt(banking_industry[:,2])
sq

array([26.26785107, 29.41088234, 17.66352173, 17.40689519, 26.13426869,
       19.20937271, 26.05762844, 22.24859546, 17.3781472 , 27.80287755])

In [194]:
#**Q9.4:** Calculate the exponential of all transaction counts
ex=np.exp(banking_industry[:,3])
ex

array([5.32048241e+11, 1.95729609e+11, 5.98741417e+04, 6.56599691e+07,
       4.42413392e+05, 5.18470553e+21, 1.58601345e+15, 4.72783947e+18,
       2.41549528e+07, 1.58601345e+15])

In [195]:
#**Q9.5:** Calculate the natural logarithm of all account balances
lg=np.log(banking_industry[:,1])
lg

array([4.84999695, 8.96249677, 8.88648797, 8.51048273, 8.96331516,
       8.2170633 , 8.81030748, 9.00313291, 8.62724509, 9.11370612])

In [ ]:
### Question 10: Advanced Operations

In [196]:
#**Q10.1:** Calculate the cumulative sum of account balances
cms=np.cumsum(banking_industry[:,1])
cms

array([  127.74,  7932.56, 15166.13, 20132.69, 27943.9 , 31647.51,
       38350.49, 46479.  , 52060.68, 61139.56])

In [197]:
#**Q10.2:** Calculate the cumulative product of transaction counts
cm=np.cumprod(banking_industry[:,3])
cm

array([2.70000000e+01, 7.02000000e+02, 7.72200000e+03, 1.38996000e+05,
       1.80694800e+06, 9.03474000e+07, 3.16215900e+09, 1.35972837e+11,
       2.31153823e+12, 8.09038380e+13])

In [198]:
#**Q10.3:** Calculate the difference between consecutive account balances
cn=np.diff(banking_industry[:,1])
cn

array([ 7677.08,  -571.25, -2267.01,  2844.65, -4107.6 ,  2999.37,
        1425.53, -2546.83,  3497.2 ])

In [199]:
#**Q10.4:** Calculate the gradient of account balances
gt=np.gradient(banking_industry[:,1])
gt

array([ 7677.08 ,  3552.915, -1419.13 ,   288.82 ,  -631.475,  -554.115,
        2212.45 ,  -560.65 ,   475.185,  3497.2  ])

In [ ]:
#**Q10.5:** Calculate the histogram of account balances with 5 bins


In [ ]:
### Question 11: Random Numbers and Simulation

In [200]:
#**Q11.1:** Generate 6 random integers between 1 and 1000
rd=np.random.randint(1,1001,6)
rd

array([486, 159,  51, 343, 662, 925])

In [206]:
#**Q11.2:** Generate 6 random floats between 0 and 1
rf=np.random.random(6)
rf

array([0.79652486, 0.30916005, 0.47462647, 0.76506303, 0.21308398,
       0.36877864])

In [204]:
#**Q11.3:** Generate 6 random numbers from normal distribution (mean=700, std=100)
rn=np.random.normal(0,1,6)
rn


array([-0.38143639,  0.31527054, -0.81669154,  2.50788762,  0.96012204,
       -0.27444669])

In [208]:
#**Q11.4:** Shuffle the `banking_data` rows randomly
sf=banking_industry.copy()
np.random.shuffle(sf)
sf

array([[9.02000e+02, 7.80482e+03, 8.65000e+02, 2.60000e+01, 1.80000e+01],
       [9.05000e+02, 7.81121e+03, 6.83000e+02, 1.30000e+01, 1.70000e+01],
       [9.10000e+02, 9.07888e+03, 7.73000e+02, 3.50000e+01, 3.00000e+00],
       [9.01000e+02, 1.27740e+02, 6.90000e+02, 2.70000e+01, 1.10000e+01],
       [9.08000e+02, 8.12851e+03, 4.95000e+02, 4.30000e+01, 1.60000e+01],
       [9.00000e+02, 7.23357e+03, 3.12000e+02, 1.10000e+01, 1.60000e+01],
       [9.06000e+02, 3.70361e+03, 3.69000e+02, 5.00000e+01, 1.40000e+01],
       [9.07000e+02, 6.70298e+03, 6.79000e+02, 3.50000e+01, 7.00000e+00],
       [9.04000e+02, 4.96656e+03, 3.03000e+02, 1.80000e+01, 1.90000e+01],
       [9.09000e+02, 5.58168e+03, 3.02000e+02, 1.70000e+01, 2.10000e+01]])

In [209]:
#**Q11.5:** Set random seed to 123 and generate 4 random numbers
np.random.seed(123)
srs=np.random.random(4)
srs

array([0.69646919, 0.28613933, 0.22685145, 0.55131477])

In [ ]:
### Question 12: Linear Algebra Operations

In [213]:
#**Q12.1:** Calculate the dot product of account balance and credit score columns
dp=np.dot((banking_industry[:,1]),(banking_industry[:,2]))
dp


34581317.41

In [217]:
#**Q12.2:** Calculate the cross product of first two rows
cp=np.cross(banking_industry[0,:3],banking_industry[1,:3])
cp

array([-5274830.7 ,  -156985.  ,  6916921.34])

In [218]:
#**Q12.3:** Calculate the norm (magnitude) of the account balance column
nor=np.linalg.norm(banking_industry[:,1])
nor

20910.244952941128

In [223]:
#**Q12.4:** Create a 3x3 matrix and calculate its determinant
mat=np.array([[1,4,2],[2,5,6],[4,3,6]])
cd=np.linalg.det(mat)
mat
cd

32.000000000000014

In [224]:
#**Q12.5:** Calculate the inverse of the 3x3 matrix
im=np.linalg.inv(mat)
im

array([[ 0.375  , -0.5625 ,  0.4375 ],
       [ 0.375  , -0.0625 , -0.0625 ],
       [-0.4375 ,  0.40625, -0.09375]])