In [55]:
import numpy as np
import pandas as pd

In [56]:

# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
retail_data = np.array([
    [1, 26000, 360, 1200, 10],
    [2, 34000, 450, 1500, 15],
    [3, 29000, 380, 1100, 18],
    [4, 49000, 520, 1660, 20],
    [5, 38000, 420, 1400, 12],
    [6, 27000, 360, 1300, 19],
    [7, 39000, 480, 1710, 18],
    [8, 33000, 470, 1250, 14],
    [9, 41000, 550, 1890, 25],
    [10, 37000, 410, 1450, 11]
])

print(retail_data)

[[    1 26000   360  1200    10]
 [    2 34000   450  1500    15]
 [    3 29000   380  1100    18]
 [    4 49000   520  1660    20]
 [    5 38000   420  1400    12]
 [    6 27000   360  1300    19]
 [    7 39000   480  1710    18]
 [    8 33000   470  1250    14]
 [    9 41000   550  1890    25]
 [   10 37000   410  1450    11]]


In [57]:
#1. What is the **total revenue** generated across all stores?
retail_data[:,4].sum()

162

In [58]:
#2. Which store recorded the **highest sales**?
retail_data[:,1].argmax()+1

4

In [59]:
#3. Which store recorded the **lowest sales**?
retail_data[:,1].argmin()+1

1

In [60]:
#4. What is the **average daily sales** per store?
P=retail_data[:,1].mean()/10
P

3530.0

In [61]:
#5. How many stores achieved sales **above ₹35,000**?
N=retail_data[retail_data[:,1]>35000]
N[:,0]

array([ 4,  5,  7,  9, 10])

In [62]:
#6. Which store had the **highest customer footfall**?
retail_data[:,2].argmax()+1

9

In [63]:
#7. What is the **average number of customers** per store?
retail_data[:,2].mean()/10

44.0

In [64]:
#8. How many stores have **more than 450 customers**?
N=retail_data[retail_data[:,2]>450]
N[:,0]

array([4, 7, 8, 9])

In [65]:
#9. Which store has the **lowest customer count**?
retail_data[:,2].argmin()+1

1

In [66]:
#10. Is there any store where **high sales do not correspond to high customers**?
N=retail_data[:,1].mean()
M=retail_data[:,2].mean()
L=retail_data[(retail_data[:,1]>N) & (retail_data[:,2]<M)]
L

array([[    5, 38000,   420,  1400,    12],
       [   10, 37000,   410,  1450,    11]])

In [67]:
#11. What is the **total inventory** across all stores?
retail_data[:,3].sum()

14460

In [68]:
#12. Which store has the **highest inventory stock**?
retail_data[:,3].argmax()+1

9

In [69]:
#13. How many stores have **inventory less than 1300 units**?
N=retail_data[retail_data[:,3]<1300]
N[:,0]

array([1, 3, 8])

In [70]:
#14. Which store has the **highest return rate** (returns ÷ inventory)?
(retail_data[:,4]/retail_data[:,3]).argmax()+1

3

In [71]:
#15. Which stores have **returns greater than 15 units**?
N=retail_data[retail_data[:,4]>15]
N[:,0]

array([3, 4, 6, 7, 9])

In [72]:
#16. Is there a **positive correlation** between sales and customers?
N=retail_data[:,1]
M=retail_data[:,2]
L=(np.corrcoef(N,M))
print(L)

[[1.        0.8340604]
 [0.8340604 1.       ]]


In [73]:
#17. Which store has **high customer visits but low sales**?
N=retail_data[:,2].mean()
M=retail_data[:,1].mean()
L=retail_data[(retail_data[:,2]>N) & (retail_data[:,1]<M)]
L

array([[    2, 34000,   450,  1500,    15],
       [    8, 33000,   470,  1250,    14]])

In [74]:
#18. Which store has **low customers but high sales**?
N=retail_data[:,2].mean()
M=retail_data[:,1].mean()
L=retail_data[(retail_data[:,2]<N) & (retail_data[:,1]>M)]
L

array([[    5, 38000,   420,  1400,    12],
       [   10, 37000,   410,  1450,    11]])

In [75]:
#19. How many stores have **sales per customer above ₹90**?
retail_data[(retail_data[:,1])/(retail_data[:,2])>90]

array([[    4, 49000,   520,  1660,    20],
       [    5, 38000,   420,  1400,    12],
       [   10, 37000,   410,  1450,    11]])

In [76]:
#20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?
N=retail_data[:,2].argmin()+1
M=retail_data[:,3].argmax()+1
L=(N,M)
print(L)

(1, 9)


In [77]:
#21. If profit margin is **20% of sales**, what is the **profit per store**?
N=retail_data[:,1]*0.20
N

array([5200., 6800., 5800., 9800., 7600., 5400., 7800., 6600., 8200.,
       7400.])

In [78]:
#22. Which store has the **highest profit**?

L=(retail_data[:,1]-retail_data[:,4]).argmax()+1
L

4

In [79]:
#23. Which store has the **lowest profit**?
K=(retail_data[:,1]-retail_data[:,4]).argmin()+1
K

1

In [80]:
#24. If sales increase by **10% next month**, what are the **new sales figures**?
N=retail_data[:,1]*0.10
O=retail_data[:,1]+N
O

array([28600., 37400., 31900., 53900., 41800., 29700., 42900., 36300.,
       45100., 40700.])

In [81]:
#25. How will **total profit** change with the 10% sales increase?
H=sum(O)
print(H)

388300.0


In [85]:
#26. Which stores need **inventory restocking** based on sales and current stock?
W=retail_data[:,1].mean()
Q=retail_data[:,3].mean()
B=retail_data[(retail_data[:,1]>W) & (retail_data[:,3]<Q)]
B


array([[    5, 38000,   420,  1400,    12]])

In [ ]:
#27. Which stores show **high returns percentage** and might require **quality checks**?


In [86]:
#28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
L=(retail_data[:,1],retail_data[:,2],retail_data[:,3])
N=np.sum(L,axis=0)
M=np.argmax(N)+1
print(M)


4


In [ ]:
#29. Which store is the **worst performer overall**?
N=np.sum(retail_data,axis=0)
M=np.argmin(N)+1
print(M)

1


In [ ]:
#30. Which stores can be considered for **expansion** based on strong sales and customer metrics?
